name: Render KiCad files
on: [push]
jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Render PDF
        uses: emilymclean/kicad-pdf@v1.0.4
        with:
          input-files: neogeo_controller_tester.kicad_sch
          output-file: generated/neogeo_controller_tester_schematic.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: testing
          path: generated/neogeo_controller_tester_schematic.pdf
