name: Render KiCad files
on: [push]
jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Render project
        uses: sparkengineering/kicad-action@v3
        id: production
        with:
          kicad_sch: neogeo_controller_tester.kicad_sch
          sch_pdf: true
          sch_bom: false
          kicad_pcb: neogeo_controller_tester.kicad_pcb
          pcb_gerbers: true
      - name: Upload production files
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        with:
          name: Production files
          path: |
            ${{ github.workspace }}/sch.pdf
            ${{ github.workspace }}/gbr.zip
